# meta settings
title: Zac Pearson
description: >
    Full-stack web developer and student at Hamline University.
baseurl: ""
url: "http://zacpearson.me"
email: zacfpearson@gmail.com
twitter_username: Zacilles
github_username:  zacfpearson

# build settings
markdown: kramdown
