FROM golang:alpine

RUN apk update && apk add git g++ gcc make && mkdir /src && cd /src && git clone https://github.com/gohugoio/hugo.git && \
    cd hugo && go install --tags extended

ENTRYPOINT [""]